# Generated by Django 5.1.4 on 2026-05-10 10:23

import secrets

from django.db import migrations, models


def populate_pair_invite_codes(apps, schema_editor):
    Pair = apps.get_model("play", "Pair")
    for pair in Pair.objects.filter(invite_code=""):
        code = secrets.token_urlsafe(8)
        while Pair.objects.filter(invite_code=code).exists():
            code = secrets.token_urlsafe(8)
        pair.invite_code = code
        pair.save(update_fields=["invite_code"])


class Migration(migrations.Migration):

    dependencies = [
        ('play', '0005_fun_prata_terms'),
    ]

    operations = [
        migrations.AddField(
            model_name='pair',
            name='invite_code',
            field=models.CharField(blank=True, max_length=16),
        ),
        migrations.AddField(
            model_name='pair',
            name='invited_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='pair',
            name='invited_name',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='pair',
            name='invited_phone',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='pair',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending partner'), ('confirmed', 'Confirmed'), ('ad_hoc', 'Ad hoc')], default='confirmed', max_length=16),
        ),
        migrations.RunPython(populate_pair_invite_codes, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='pair',
            name='invite_code',
            field=models.CharField(blank=True, max_length=16, unique=True),
        ),
    ]
