# Generated by Django 5.1.4 on 2026-05-16 08:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('play', '0008_sessionphoto'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='pratasession',
            name='challenger_player',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='challenged_singles_sessions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pratasession',
            name='match_type',
            field=models.CharField(choices=[('singles', 'Singles'), ('doubles', 'Doubles')], default='doubles', max_length=16),
        ),
        migrations.AlterField(
            model_name='pratasession',
            name='host_pair',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='hosted_sessions', to='play.pair'),
        ),
    ]
