# Generated by Django 5.1.4 on 2026-05-16 08:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('play', '0009_pratasession_challenger_player_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='matchresult',
            name='losing_player',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lost_singles_results', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='matchresult',
            name='winner_side',
            field=models.CharField(choices=[('host', 'Host side'), ('challenger', 'Challenger side')], default='host', max_length=16),
        ),
        migrations.AddField(
            model_name='matchresult',
            name='winning_player',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='won_singles_results', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='matchresult',
            name='losing_pair',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='lost_results', to='play.pair'),
        ),
        migrations.AlterField(
            model_name='matchresult',
            name='winning_pair',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='won_results', to='play.pair'),
        ),
        migrations.CreateModel(
            name='MatchSetScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('set_number', models.PositiveSmallIntegerField()),
                ('host_score', models.PositiveSmallIntegerField()),
                ('challenger_score', models.PositiveSmallIntegerField()),
                ('result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='set_scores', to='play.matchresult')),
            ],
            options={
                'ordering': ('set_number',),
                'unique_together': {('result', 'set_number')},
            },
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField()),
                ('badges', models.JSONField(default=list)),
                ('text', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_testimonials', to=settings.AUTH_USER_MODEL)),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='given_testimonials', to=settings.AUTH_USER_MODEL)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='testimonials', to='play.pratasession')),
            ],
            options={
                'ordering': ('-created_at',),
                'unique_together': {('session', 'reviewer', 'reviewed_user')},
            },
        ),
    ]
